version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - DB_URI=mongodb://user:password@db:27017/database
    env_file:
      - ./backend/.env
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork
    ports:
      - "27017:27017"

volumes:
  mongodb_data: {}

networks:
  mynetwork:
    driver: bridge
